---
name: AMR2MQTT
url: https://github.com/mdegat01/addon-amr2mqtt
version: dev
slug: amr2mqtt
arch:
  - aarch64
  - amd64
  - armv7
  - armhf
description: AMR2MQTT for Home Assistant
uart: true
udev: true
usb: true
services:
  - mqtt:want
map:
  - ssl
options:
  watched_meters: []
  wh_multiplier: 1000
  message_types:
    - scm
  mqtt: {}
schema:
  watched_meters:
    - int
  wh_multiplier: int(1,)
  readings_per_hour: int(1,)?
  message_types:
    - list(scm|idm)
  mqtt:
    host: str?
    port: port?
    ca: str?
    cert: str?
    key: str?
    username: str?
    password: password?
    client_id: str?
    base_topic: str?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
