---
name: AMR2MQTT
url: https://github.com/mdegat01/addon-amr2mqtt
version: dev
slug: amr2mqtt
arch:
  - aarch64
  - amd64
  - armv7
  - armhf
description: AMR2MQTT for Home Assistant
uart: true
udev: true
usb: true
services:
  - mqtt:want
map:
  - ssl
options:
  meters: []
  mqtt: {}
schema:
  meters:
    - id: int
      protocol: list(idm|netidm|r900|scm|scm+)
      name: str?
      type: list(gas|water|electric)?
      reading_multiplier: float(0,)?
      reading_unit_of_measurement: str?
  mqtt:
    host: str?
    port: port?
    ca: str?
    cert: str?
    key: str?
    username: str?
    password: password?
    client_id: str?
    base_topic: match(^[^+#]{1,65535}$)?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  home_assistant_discovery_enabled: bool?
  home_assistant_discovery_prefix: match(^[^+#]{1,65535}$)?
