---
name: AMRIDM2MQTT
url: https://github.com/mdegat01/addon-amridm2mqtt
version: dev
slug: amridm2mqtt
arch:
  - aarch64
  - amd64
  - armv7
  - armhf
description: AMRIDM2MQTT for Home Assistant
uart: true
services:
  - mqtt:want
map:
  - ssl
options:
  watched_meters: []
  wh_multiplier: 1000
  readings_per_hour: 12
  mqtt: {}
schema:
  watched_meters:
    - int
  wh_multiplier: int(1,)
  readings_per_hour: int(1,)
  mqtt:
    host: str?
    ca: str?
    cert: str?
    key: str?
    username: str?
    password: password?
    client_id: str?
    base_topic: str?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
